from collections.abc import AsyncIterator
from typing import Protocol
from decimal import Decimal

from crypto_bot.domain.enums import PositionSide
from crypto_bot.domain.models import (
    ExchangeSnapshot, ExecutionEvent, MarketEvent, OrderIntent, OrderObservation,
    SubmitResult, SymbolRules,
)


class ExchangePort(Protocol):
    async def fetch_snapshot(self) -> ExchangeSnapshot: ...
    async def fetch_rules(self, symbol: str) -> SymbolRules: ...
    def market_events(self, symbols: tuple[str, ...]) -> AsyncIterator[MarketEvent]: ...
    def execution_events(self) -> AsyncIterator[ExecutionEvent]: ...
    async def submit_entry(self, intent: OrderIntent) -> SubmitResult: ...
    async def find_order(self, intent: OrderIntent) -> OrderObservation | None: ...
    async def cancel_order(self, intent: OrderIntent) -> SubmitResult: ...
    async def submit_protection(self, intent: OrderIntent) -> SubmitResult: ...
    async def reduce_position(self, symbol: str, side: PositionSide,
                              quantity: Decimal, client_id: str) -> SubmitResult: ...
